### ISSUE TITLE
Release a new version and bump Bower version in coordination

### ISSUE THREAD

**Issue by notmessenger** [kurko/ember-localstorage-adapter#109]
All of the changes after commit https://github.com/kurko/ember-localstorage-adapter/commit/d64cf02c764cc7d7fb9cb91e63d7ca05160f9db3 are not gotten when running `bower install ember-localstorage-adapter` because a new version has not been released.  So while the README.md says that this adapter is "Compatible with Ember Data 1.0.beta.16" the code required to be so is not actually installed.

**Comment by kurko** [comment]
Will do it tonight cc https://github.com/kurko/ember-localstorage-adapter/pull/107#issuecomment-88502439

**Comment by chrisvdp** [comment]
ping

**Comment by mylen** [comment]
:+1:

**Comment by kurko** [comment]
Release 0.5.3 is out :)

Sorry for the delay.
