### ISSUE TITLE
DEPRECATION: You called _createSnapshot on what's already a DS.Snapshot

### ISSUE THREAD

**Issue by hussfelt** [kurko/ember-localstorage-adapter#110]
```
DEBUG: -------------------------------
DEBUG: Ember      : 1.11.1
DEBUG: Ember Data : 1.0.0-beta.16
DEBUG: jQuery     : 1.11.2
DEBUG: -------------------------------
```

DEPRECATION: You called _createSnapshot on what's already a DS.Snapshot. You shouldn't manually create snapshots in your adapter since the store passes snapshots to adapters by default.

**Comment by kurko** [comment]
hmmm right. Any chance you can send us a PR? It's a matter of replacing `record._createSnapshot()` with `snapshot` I think.

**Comment by hussfelt** [comment]
@kurko Thanks! I actually went ahead and did that now in our local environment!
Then when forking I noticed this was already done :-)

https://github.com/kurko/ember-localstorage-adapter/commit/28d6aaac2f3d1cba929b7e0d15bf35abc806c128

Both the issues I had are gone with the latest master!
Tag a new release that is compatible with ember-data beta 16? :)
