### ISSUE TITLE
Support Ember Data beta.17

### ISSUE THREAD

**Issue by ujamer** [kurko/ember-localstorage-adapter#116]
Hi, after upgrading Ember Data to beta 17, this adapter is broken. The console gives me this error: `TypeError: snapshot.hasMany(...) is undefined`. Seems like they changed the syntax for `hasMany()` function call. 

Once I replaced the line `json[payloadKey] = snapshot.hasMany(key).mapBy('id');` with `json[payloadKey] = snapshot.hasMany(key, { ids: true });` things are functional again.

Could we update adapter to support beta 17? Thanks!

**Comment by zekefast** [comment]
I have same error. After `ember-data` update from `1.0.0-beta.16.1` to `1.0.0-beta.17` I see
`TypeError: snapshot.hasMany(...) is undefined` error. It looks like it bubbled from `serializeHasMany` method.
As well it appears only on attempt to save a form which is logically correct as I error appears on serialization. I use `DS.EmbeddedRecordsMixin` for model which I try to save, dunno if it helps.

**Comment by kurko** [comment]
> Could we update adapter to support beta 17? 

Yep. Can you open a PR for that?

**Comment by ujamer** [comment]
Sure.

**Comment by kurko** [comment]
Lovely.
