### ISSUE TITLE
findAll returns empty array always

### ISSUE THREAD

**Issue by igorrKurr** [kurko/ember-localstorage-adapter#120]
Hi!

I used this adapter in my app. 
And i had such issue.

These steps i did to get it:
1 - setup adapter, serializer, create model 
2 - i populate my localStorage manually. It contains  
```json
{"user":{"users":[{"firstName":"Telly","lastName":"Beatty","gender":"male","id":1}]}}
```
3 - call `this.store.find('user')

And I get empty array.

I briefly take look at localStorage adapter source and see this line https://github.com/kurko/ember-localstorage-adapter/blob/master/localstorage_adapter.js#L220. 

Here `.records` property called on namespace.
And i got `{users: [...]}` hash from here https://github.com/kurko/ember-localstorage-adapter/blob/master/localstorage_adapter.js#L217, and it doesn't contains any  `records ` property. 

So I think that problem is here, but maybe i did something wrong?

**Comment by igorrKurr** [comment]
hi once again!

json i populated localStorage is wrong:
```json
{"user":{"users":[{"firstName":"Telly","lastName":"Beatty","gender":"male","id":1}]}}
```

and should be:
```json
{"user":{"records":{"1":{"id":"1","firstName":"Lavada","lastName":"Schumm","gender":"male"},"2":{"id":"2","firstName":"Kelton","lastName":"Vandervort","gender":"female"}}}}
```

My mistake, sorry :grimacing:

**Comment by kurko** [comment]
:+1:
