### ISSUE TITLE
unloadAll() doesnt work

### ISSUE THREAD

**Issue by skaterdav85** [kurko/ember-localstorage-adapter#128]
```js
this.store.unloadAll();
```

Error while processing route: orders Cannot read property 'typeKey' of undefined TypeError: Cannot read property 'typeKey' of undefined

I then tried to unload each model type individually:

```js
this.store.unloadAll('order-item');
```

This doesn't produce an error but it also doesn't work. Any ideas for workarounds?

**Comment by kurko** [comment]
Not really. For `TypeError: Cannot read property 'typeKey' of undefined`, can you follow the execution until you find the line that's causing this?

**Comment by kurko** [comment]
https://github.com/kurko/ember-localstorage-adapter/issues/125 is related. I'm closing this. If you think it's a separate issue, please reopen.
