### ISSUE TITLE
Docs say install with npm, reference bower

### ISSUE THREAD

**Issue by justinph** [kurko/ember-localstorage-adapter#96]
The README.md presently says the following:

> ```sh
npm install --save-dev ember-localstorage-adapter
```

> Then in Brocfile.js import it before module.exports:

> ```js
app.import('bower_components/ember-localstorage-adapter/localstorage_adapter.js');
> module.exports = app.toTree();
```

Installing with npm puts ember-localstorage-adapter in `node_modules`, not in `bower_components`. One of these paths is wrong... Unless I'm missing something, commit 5c9d272 seems to have caused this, or only half updated the docs.

**Comment by kimroen** [comment]
Trees that are included in the `treeFor` hook is available under `vendor`, actually, so it would be available as `vendor/ember-localstorage-adapter/localstorage_adapter.js`:
https://github.com/kurko/ember-localstorage-adapter/blob/dc15b2f21ecdf23d42ae6a72e1d04c82bcd12f6e/ember-addon-main.js#L8

That works.

Also though, according to their `included`-hook, it should be added automatically:
https://github.com/kurko/ember-localstorage-adapter/blob/dc15b2f21ecdf23d42ae6a72e1d04c82bcd12f6e/ember-addon-main.js#L28

But that doesn't seem to work. Not sure why.

**Comment by kimroen** [comment]
Actually, I was wrong on that last part - it does get included automatically. Nothing needs to be added to the Brocfile at all.

**Comment by ATMartin** [comment]
I submitted #102 to address this. @justinph, thanks for bringing it up and @kimroen, thanks for discovering the Brocfile addition wasn't needed!

**Comment by kurko** [comment]
#102 is merged :smile:
