### ISSUE TITLE
SecurityError in Safari when storage is disabled

### ISSUE THREAD

**Issue by dfreeman** [kurko/ember-localstorage-adapter#97]
When a user has selected to block "cookies and website data" in Safari, attempting to access localStorage (annoyingly) throws a SecurityError.

![image](https://cloud.githubusercontent.com/assets/108688/5581088/28c2523e-9022-11e4-876f-fee843c3335e.png)

For our particular use case, it would be completely fine to simply have the state live in memory and get blown away as soon as the user leaves the page.

However, you could also imagine wanting a way to handle the situation in application code, perhaps warning the user. Maybe based on an event emitted by the adapter, similar to the `QUOTA_EXCEEDED_ERR` case?

**Comment by kurko** [comment]
Can you create a PR for that?
