### ISSUE TITLE
LocalStorageAdaptor sitting beside RESTAdapter

### ISSUE THREAD

**Issue by ksnyde** [kurko/ember-localstorage-adapter#98]
I wonder if it is possible to include a little design philosophy about how one might leverage BOTH the RESTAdaptor and the LocalStorageAdaptor within a given application. It would be really nice to see something about this strategy (which I would have thought would be quite common) in the `README.md`. Even if the answer is "there is no current way of doing this"? :)

The two patterns I'm interested in is:

1. **Segmented Models** - there are some models which are backed by the LSA and others which are backed by the REST adapter but this is fully atomic at the model level and *no* relationships are defined that cross these boundaries. 
1. **LSA Backed REST** - I'd really love to see a smart way of using LSA as a caching layer for reference data and in this strategy you would use LSA as the cache for results with some background refreshing of this data being provided by the REST adapter. I can imagine this scenario is unreasonably complex but I'd love to hear of cases where people have made progress on this.

**Comment by justinph** [comment]
You can do item 1 in your app without issue. You just need to have a different serializer for your REST based models and your localStorage based models. 

Item 2 is harder and I'm not sure why you'd want to do that. If you're using ember data, it takes care of caching for you in memory. Localstorage might offer a boost in speed if your dataset is large, but if it is very large localstorage probably isn't a good fit.

**Comment by shekyboy** [comment]
Item #2 from @ksnyde list is perfect for mobile apps which use HTML5 within a native wrapper.
The app can be extremely responsive by displaying local data to the user and in the background fetch updates from the server.

Offline first is becoming a need. This will become common place going forward.

**Comment by kurko** [comment]
@ksnyde this not LS related, but you should definitely check
kurko/ember-sync

**Comment by Leooo** [comment]
+1 for the use case of fetching models from LS, then from a REST API if models are empty: aiming to populate LS using SSE as much as possible, and fallback to a JSON server request when no other choice. Doing it manually now, but I suppose it would be better to use nested adapters for this case.

**Comment by kurko** [comment]
Yeah. Check ember-sync. I'm closing given it's unrelated to this adapter.
