### ISSUE TITLE
DS.LSSerializer for ember-cli

### ISSUE THREAD

**Issue by kgish** [kurko/ember-localstorage-adapter#99]
I am trying to migrate an existing ember app to ember-cli, in my orignal `app.js` file:
```
App.FooSerializer = DS.LSSerializer.extend();
```
Transformed to ember-cli `app/adapters/foo.js` something like this:

```
import ??? from '???';

export default ???.extend();
```
What should the `???` be?

**Comment by willrax** [comment]
Should be something like this:

```javascript
import DS from "ember-data";

export default DS.LSAdapter.extend({
  namespace: "app-name"
});
```

**Comment by kgish** [comment]
That's correct, it works now.
